### ISSUE TITLE
Sync Task model fields: start, end and timing_rule

### ISSUE THREAD

**Issue by moshthepitt** [onaio/tasking#11]
The `timing_rule` accepts and stores a [standard rrule](https://tools.ietf.org/html/rfc2445), but we also have a `start` and `end` field for task models.

[`rrule` in turn defines](http://dateutil.readthedocs.io/en/stable/rrule.html) a `dstart` and `until` parameter.

We need to ensure that the `start` and `end ` fields are in sync with the `timing_rule` `dstart` and `until` parameters.

For instance, if a user attempts to create a Task and provides the `start` as well as `timing_rule` with `dstart` different from `start`, we should not allow this.

**Comment by urbanslug** [comment]
I think the serializer should only expose the `timing_rule` (RRule) field and then generate the `start` and `end` fields from the `timing_rule`.

**Comment by moshthepitt** [comment]
I think we should expose all three `start`, `end` and `timing_rule`.  This is to handle all possible cases i.e. tasks that have a start and an end but no recurrence, or tasks that just have a timing rule.

For validation, we will need to ensure:

1. If `dtstart` and/or `until` differ from `start` and/or `end` then we raise an error
2. If `dtstart` and/or `until` are provided they should be used in place of `start` and/or `end`
