### ISSUE TITLE
Handle shapefile uploads from API

### ISSUE THREAD

**Issue by moshthepitt** [onaio/tasking#134]

**Comment by moshthepitt** [comment]
To replicate this issue:

- install kaznet web
- send a POST to the kaznet web API to create a new location - the POST should include a shapefile upload.  
- you will get a 500 caused on the tasking library

**Comment by lincmba** [comment]
Uploads work fine on Postman because it's aware of the filepath. However, the frontend has no access to the filepath.

Solution: 

- Convert file to binary on frontend

- Send binary data to api

- Have tasking handle the binary data conversion to zipfile then shapefile

**Comment by moshthepitt** [comment]
Fixed in #137
