### ISSUE TITLE
Upgrade to django-filter v2

### ISSUE THREAD

**Issue by moshthepitt** [onaio/tasking#136]

**Comment by moshthepitt** [comment]
See https://django-filter.readthedocs.io/en/master/guide/migration.html#migrating-to-2-0

**Comment by DavisRayM** [comment]
Would upgrading `django-filter` to v2 mean that the package will no longer support `python2.7`? since the version isn't compatible with python 2.

**Comment by moshthepitt** [comment]
@DavisRayM does v2 of django-filter work only with python3?

**Comment by DavisRayM** [comment]
@moshthepitt https://github.com/carltongibson/django-filter/issues/954#issuecomment-407119527 from this issue it seems like v2.0 doesn't support python2

**Comment by moshthepitt** [comment]
@DavisRayM  That sucks for us.  We probably will not be able to switch to v2 of django-filter for at least a few (or a lot) months

**Comment by DavisRayM** [comment]
@moshthepitt Nice, i'd like to work on this. I'll create a PR for this soon.

**Comment by DavisRayM** [comment]
This issue is currently being blocked by this issue on [django rest framework gist](https://github.com/djangonauts/django-rest-framework-gis/issues/170)
