### ISSUE TITLE
Add Documentation for the tasking models 

### ISSUE THREAD

**Issue by moshthepitt** [onaio/tasking#88]
- [ ] Task
- [ ] Submission
- [ ] Project
- [ ] Location
- [ ] SegmentRule
- [ ] TaskOccurrence

The documentation should be:

- a description of the model base class (the abstract model class) and what it is supposed to do
-  a description of the concrete model and its fields and any methods it may have

**Comment by moshthepitt** [comment]
Add these in individual files in a `models` directory within `docs`

**Comment by DavisRayM** [comment]
@urbanslug When creating the Submissions model documentation. Please reflect the changes made by this PR.  #91

**Comment by urbanslug** [comment]
I will
